### PR TITLE
fix(ui): debounce the scroll event to make chrome happy

### LINKED ISSUE #3893: "find in page" misbehaves with Chrome/Mac
From Amanda Baber:
> This is happening in Chrome with Mac versions 11 and 12. (Safari is fine.)
> 
> When I use command-F to find text at https://datatracker.ietf.org/iesg/agenda/ or https://datatracker.ietf.org/wg/, Chrome tells me how many occurrences there are, and if I scroll down the page, they’re highlighted. However, it won’t jump to them. The “previous” and “next” up/down arrows don’t work.

### PR DESCRIPTION
**Pull request by larseggert**
Fixes #3893, #3841

### CODE REVIEW

File: ietf/static/js/ietf.js [hunk 1]
```diff
@@ -244,15 +246,17 @@ $(function () {
...
+                // otherwise the main view doesn't scroll?
+                .on("scroll", debounce(function () {
                     const item = $('#righthand-nav')
                         .find(".active")
                         .last();
                     if (item.length) {
                         item[0].scrollIntoView({ block: "center" });
                     }
-                });
+                }, 20));
```
Comment (NGPixel) [inline ietf/static/js/ietf.js:259]: I would suggest using a value like `100` ms debounce if it achieves the same result. I've found using values under 100 ms to be unreliable in many scenarios.

File: package.json [hunk 2]
```diff
@@ -18,6 +18,7 @@
     "jquery-ui-dist": "1.13.0",
     "js-cookie": "3.0.1",
     "list.js": "2.3.1",
+    "lodash.debounce": "4.0.8",
```
Comment (NGPixel) [inline package.json:21]: As suggested above, replace with the full `lodash` library instead.

**Review by NGPixel — CHANGES_REQUESTED** [review]

**Review by NGPixel — APPROVED** [review]

**Comment by larseggert** [comment]
The failing check should be fixed by #3975
