### PR TITLE
fix: Sort RFCs by date

### LINKED ISSUE #7740: Sorting RFC's by date on Datatracker profile pages is incorrect
### Describe the issue

Current behaviour: When visiting a user profile page, if you click to sort RFC's by date, it sorts it based on the Month Year string. This results in entries being sorted by Month and then year. eg: April 2024 can appear before June 2000.

Expected behaviour: Sort by year and then by month, thus sorting in chronological order.

Changing the displayed dates to a YYYY-MM-DD format for example may be a viable fix.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by holloway**
Fixes #7740

Allows sorting by `data-sort-number` attribute on the cell, rather than by the content of the cell which might be formatted.

### CODE REVIEW

**Review by NGPixel — DISMISSED** [review]

File: ietf/static/js/list.js [hunk 1]
```diff
@@ -5,8 +5,10 @@ import {
 function text_sort(a, b, options) {
 
     function prep(e, options) {
-        return $($.parseHTML(e.values()[options.valueName]))
-            .text()
+        const el = $($.parseHTML(e.values()[options.valueName]));
```
Comment (jennifer-richards) [inline ietf/static/js/list.js:8]: `el` gato 🐱

**Review by jennifer-richards — DISMISSED** [review]

**Review by jennifer-richards — APPROVED** [review]
