### PR TITLE
fix: Update timezone on the interim create page

### LINKED ISSUE #3898: Interim meeting time entry
### What happened?

When creating an interim meeting, the default timezone is 'UTC'. However, if this isn't modified before the meeting is created, the meeting ends up being scheduled in the browser's local timezone. This results in a meeting request at the wrong time.

The 'Time' component does indicate 'local time', but it's not clear what that is in relation to -- is it 'local' to the meeting being scheduled, or 'local' to the user? The second interpretation isn't intuitive.

### What browser(s) are you seeing the problem on?

Safari

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

### PR DESCRIPTION
**Pull request by meadmaker**
The interim creation screen will set the timezone to the timezone of
the browser.  Unfortunately, the UI element was never refreshed, so
it remained on its loaded default, thus telling the user the wrong
value.

This change adds a timezone widget refresh to the end of the function that
loads the browser's local timezone into the timezone value.

This change also adds code to update the 'Local timezone' help text
for the start time and end time input bozes to
call out the selected timezone specifically.

(Finally, it adds a newline at the end of the file, since none was present previously)

Fixes #3898

### CODE REVIEW

File: ietf/static/js/meeting-interim-request.js [hunk 1]
```diff
@@ -231,10 +233,14 @@ const interimRequest = (function() {
         },
 
         timezoneChange: function () {
+            var tzname = $(this).val();
```
Comment (jennifer-richards) [inline ietf/static/js/meeting-interim-request.js:236]: Should use `const tzname` - we're trying to rid the codebase of `var`

**Review by jennifer-richards — CHANGES_REQUESTED** [review]
Looks good, just some minor lint.

It strikes me as a little awkward that we now have to hook up the change event on the timezone input before we call `initTimeZone()`. It might be worth adding a comment to discourage someone from "helpfully" switching that around.

**Review by NGPixel — APPROVED** [review]

**Review by jennifer-richards — APPROVED** [review]
