### PR TITLE
fix: Fix table sort functionality for tables with `colspan` attributes

### LINKED ISSUE #4555: nomcom private page tables have column-sort markers that do nothing
### Describe the issue

the "nominees" page has column-sort markers (up/down) for the first table, which is summary counts, and for the second table, which are specific entries.  The first table sorts by clicking on those markers. The second table does nothing.  

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by larseggert**
Fixes #4555

### CODE REVIEW

File: ietf/static/js/list.js [hunk 1]
```diff
@@ -62,12 +60,21 @@ $(document)
                 // get field classes from first thead row
                 var fields = $(header_row)
```
Comment (rjsparks) [inline ietf/static/js/list.js:61]: I'm going to approve this, but this bit of new code is particularly hard to understand. I wonder if it could be written in a way that would promote better maintenance?

**Review by rjsparks — APPROVED** [review]
